[functions]

  [functions.emails]
  included_files = [
    "./emails/**"
  ]

[build]
publish = "."

[[headers]]
for = "/assets/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/favicon.ico"

  [headers.values]
  Cache-Control = "public, max-age=2592000"

[[headers]]
for = "/*.svg"

  [headers.values]
  Cache-Control = "public, max-age=2592000"

[[headers]]
for = "/*"

  [headers.values]
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self'; form-action 'self' https://deephull.netlify.app; base-uri 'self';"
  Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/success"
to = "/success.html"
status = 200

[[redirects]]
from = "https://www.deephull.com/*"
to = "https://deephull.com/:splat"
status = 301
force = true

[context]

  [context.production]

    [context.production.functions]

      [context.production.functions.emails]
      included_files = [
        "./emails/**"
      ]

  [context.main]

    [context.main.functions]

      [context.main.functions.emails]
      included_files = [
        "./emails/**"
      ]